apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: fksq
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: postgresql
  hostPath:
    path: /pv/postgresql
