apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
  namespace: fksq
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: sonar
  hostPath:
    path: /pv/sonar
