apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
  namespace: fksq
spec:
  storageClassName: sonar
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
