name: Helm Release Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    name: Build
    steps:
      - name: Build
        run: |
          echo "Build ... "

  scan-sast:
    runs-on: self-hosted
    name: SAST
    needs: [build]
    steps:
      - name: SAST
        run: |
          echo "SAST ... "

  scan-sca:
    runs-on: self-hosted
    name: SCA
    env:
      BUILD_PARAM1: "build param 1"
      BUILD_PARAM2: "build param 1"
    needs: [build]
    steps:
      - name: SCA
        run: |
          echo "SCA ... "
          env

  helm-release:
    runs-on: self-hosted
    name: Release Helm Chart
    needs: [build, scan-sast, scan-sca]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1

      # - name: Add Helm Repo dependencies
      #   run: |
      #     helm init
      #     helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run User chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.REPO_TOKEN }}"
          CR_SKIP_EXISTING: true
        with:
          charts_dir: charts

  post-build:
    runs-on: self-hosted
    name: Post Build
    needs: [helm-release]
    steps:
      - name: Post Build
        run: |
          echo "Post build ... "
